version: '3'

# uffizzi integration
x-uffizzi:
  ingress:
    service: cube
    port: 4000

services:
  materialize:
    image: materialize/materialized

  cube:
    image: "${CUBEJS_IMAGE}"
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_HOST=materialize
      - CUBEJS_DB_NAME=materialize
      - CUBEJS_DB_USER=materialize
      - CUBEJS_DB_PORT=6875
      - CUBEJS_DB_TYPE=materialize
      - CUBEJS_API_SECRET=SECRET
    deploy:
      resources:
        limits:
          memory: 500M
    volumes:
     - cube_volume:/cube/conf

  postgres:
    image: jbergknoff/postgresql-client
    entrypoint: ["sh", "/seed/seed.sh"]
    volumes:
      - postgres_data:/var/lib/postgresql/data/

# Volumes to persist data
volumes:
  postgres_data:
  cube_volume:

