version: '3'

# uffizzi integration
x-uffizzi:
  ingress:
    service: nginx
    port: 8081

services:
  cube:
    image: cubejs/cube
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_TYPE=postgres
      - CUBEJS_DB_HOST=localhost
      - CUBEJS_DB_NAME=ecom
      - CUBEJS_DB_USER=postgres
      - CUBEJS_DB_PASS=postgres
    deploy:
      resources:
        limits:
          memory: 1000M
    # ports:
    #   - 4000:4000  # Cube.js API and Developer Playground
    #   - 3000:3000 #SQL API
    volumes:
     - cube_volume:/cube/conf
     - .empty:/cube/conf/node_modules/@cubejs-backend
     - ./dashboard-app:/cube/conf/dashboard-app

  postgres:
   image: postgres
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=ecom
     - PGDATA=/tmp
    # - METABASE_PASSWORD=postgres
  #  deploy:
  #     resources:
  #       limits:
  #         memory: 500M
   volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql/:/docker-entrypoint-initdb.d/

  nginx:
    image: nginx:alpine
    volumes:
    - ./nginx:/etc/nginx

  # metabase:
  #  image: metabase/metabase
  #  environment:
  #       - MB_DB_TYPE=postgres
  #       - MB_DB_DBNAME=ecom
  #       - MB_DB_PORT=5432
  #       - MB_DB_USER=postgres
  #       - MB_DB_PASS=postgres
  #       - MB_DB_HOST=localhost
  #  deploy:
  #     resources:
  #       limits:
  #         memory: 1000M

# Volumes to persist data
volumes:
  postgres_data:
  cube_volume:
  .empty:

