version: '3'

# uffizzi integration
x-uffizzi:
  ingress:
    service: cube
    port: 4000

services:
  cube:
    image: "${CUBEJS_IMAGE}"
    environment:
      - CUBEJS_DEV_MODE=true
    volumes:
      - cube_data:/cube/conf
    deploy:
      resources:
        limits:
          memory: 500M
volumes:
  postgres_data:
  cube_data:


