version: '3'

# uffizzi integration
x-uffizzi:
  ingress:
    service: cube
    port: 4000

services:
  cube:
    image: "${CUBEJS_IMAGE}"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=54320
      - MB_DB_USER=metabase
      - MB_DB_PASS=12345
      - MB_DB_HOST=postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345
      - METABASE_PASSWORD=12345

  metabase:
    restart: "always"
    image: metabase/metabase
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=54320
      - MB_DB_USER=metabase
      - MB_DB_PASS=12345
      - MB_DB_HOST=postgres
# Volumes to persist data
volumes:
  postgres_volume:
