version: '3'

# uffizzi integration
x-uffizzi:
  ingress:
    service: cube
    port: 4000

services:
  cube:
    image: "${CUBEJS_IMAGE}"
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_HOST=localhost
      - CUBEJS_DB_NAME=ecom
      - CUBEJS_DB_USER=cube
      - CUBEJS_DB_PASS=12345
      - CUBEJS_DB_TYPE=postgres
      - CUBEJS_API_SECRET=SECRET
      - CUBEJS_PG_SQL_PORT=5432
      - CUBEJS_SQL_USER=cube
      - CUBEJS_SQL_PASSWORD=12345
    deploy:
      resources:
        limits:
          memory: 500M
    volumes:
     - cube_volume:/cube/conf

  postgres:
    image: postgres
    entrypoint: /seed/seed.sh
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=12345
      - METABASE_PASSWORD=12345
      - PG_DATA = /tmp

  metabase:
    image: metabase/metabase
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_USER=metabase
      - MB_DB_PASS=12345
      - MB_DB_HOST=localhost

# Volumes to persist data
volumes:
  postgres_data:
  cube_volume:

