version: '3'

# uffizzi integration
x-uffizzi:
  ingress:
    service: cube
    port: 4000

services:
  materialize:
    image: materialize/materialized:v0.26.1
  seed:
    image: jbergknoff/postgresql-client
    volumes:
      - postgres_data:/seed
    entrypoint: ["sh", "seed/seed.sh"]
  cube:
    image: "${CUBEJS_IMAGE}"
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_TYPE=materialize
      - CUBEJS_DB_HOST=materialize
      - CUBEJS_DB_PORT=6875
      - CUBEJS_DB_NAME=materialize
      - CUBEJS_DB_USER=materialize
      - CUBEJS_API_SECRET=SECRET
    volumes:
      - .cube_data:/cube/conf
    deploy:
      resources:
        limits:
          memory: 500M
volumes:
  postgres_data:
  cube_data:


