version: '3'

# uffizzi integration
x-uffizzi:
  ingress:
    service: cube
    port: 4000

services:
  cube:
    image: "${CUBEJS_IMAGE}"
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_HOST=localhost
      - CUBEJS_DB_NAME=metabase
      - CUBEJS_DB_USER=postgres
      - CUBEJS_DB_PASS=postgres
      - CUBEJS_DB_TYPE=postgres
    deploy:
      resources:
        limits:
          memory: 500M
    volumes:
     - cube_volume:/cube/conf
  postgres:
    image: postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=metabase
     - PGDATA=/tmp
     - METABASE_PASSWORD=postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      - ./postgres/:/docker-entrypoint-initdb.d/

# Volumes to persist data
volumes:
  postgres_volume:
  cube_volume:

