version: '3'

# uffizzi integration
x-uffizzi:
  ingress:
    service: cube
    port: 4000

services:
  cube:
    restart: "always"
    image: "${CUBEJS_IMAGE}"
    # ports:
    #   - 4000:4000  # Cube.js API and Developer Playground
    #   - 5432:5432  # Cube SQL API
    env_file:
      - ./config/cube.env
    volumes:
      - .:/cube/conf

  postgres:
    container_name: "postgres"
    image: postgres
    env_file:
      - ./config/postgres.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      - ./services/postgres/:/docker-entrypoint-initdb.d/

  metabase:
    container_name: "metabase"
    restart: "always"
    image: metabase/metabase
    env_file:
      - ./config/metabase.env
# Volumes to persist data
volumes:
  postgres_volume:
